services:
  aimeos-core:
    image: php:8.2-apache
    container_name: nexus_aimeos_backend
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=aimeos
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nexus_database
    environment:
      - MYSQL_DATABASE=aimeos
      - MYSQL_USER=aimeos
      - MYSQL_PASSWORD=aimeos
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: