services:
  aimeos-core:
    image: php:8.2-apache
    container_name: nexus_aimeos_backend
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=aimeos
      - DB_USER=${APP_DB_USER}
      - DB_PASSWORD=${APP_DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nexus_database
    environment:
      - MYSQL_DATABASE=aimeos
      - MYSQL_USER=${APP_DB_USER}
      - MYSQL_PASSWORD=${APP_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: